FROM ac2-registry.cn-hangzhou.cr.aliyuncs.com/ac2/base:ubuntu22.04

RUN apt-get update && \
    apt-get install -y openjdk-8-jdk wget openssh-server vim

RUN mkdir /var/run/sshd && \
    ssh-keygen -t rsa -P '' -f /root/.ssh/id_rsa && \
    cat /root/.ssh/id_rsa.pub >> /root/.ssh/authorized_keys && \
    chmod 600 /root/.ssh/authorized_keys && \
    sed -i 's/#PasswordAuthentication yes/PasswordAuthentication no/' /etc/ssh/sshd_config && \
    sed -i 's/#PubkeyAuthentication yes/PubkeyAuthentication yes/' /etc/ssh/sshd_config && \
    sed -i 's@#AuthorizedKeysFile.*@AuthorizedKeysFile .ssh/authorized_keys@' /etc/ssh/sshd_config

ENV JAVA_HOME /usr/lib/jvm/java-8-openjdk-amd64
ENV PATH $JAVA_HOME/bin:$PATH

RUN echo "export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64" >> /etc/profile
RUN echo "export JRE_HOME=$JAVA_HOME/jre" >> /etc/profile
RUN echo "export CLASSPATH=$JAVA_HOME/lib:$JRE_HOME/lib:$CLASSPATH" >> /etc/profile
RUN echo "export PATH=$JAVA_HOME/bin:$JRE_HOME/bin:$PATH" >> /etc/profile
# RUN source /etc/profile

# 设置环境变量
ENV SPARK_VERSION 3.5.3
ENV SPARK_HOME /opt/spark-$SPARK_VERSION
ENV PATH $PATH:$SPARK_HOME/bin:$SPARK_HOME/sbin

# 下载并解压Spark
RUN wget https://downloads.apache.org/spark/spark-$SPARK_VERSION/spark-$SPARK_VERSION.tgz \
    && tar -xzf spark-$SPARK_VERSION.tgz -C /opt \
    && rm spark-$SPARK_VERSION.tgz

COPY spark-defaults.conf $SPARK_HOME/conf/spark-defaults.conf

# 暴露Hadoop和Spark的端口
EXPOSE 9870 9000 8088 7077 8080 18080 9864 22

COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

# 启动脚本
CMD ["/entrypoint.sh"]