version: '3.8'

services:
  namenode:
    build: ./hadoop
    container_name: namenode
    ports:
      - "9870:9870"
      - "2222:22"
    volumes:
      - namenode-data:/usr/local/hadoop-3.3.6/tmp/namenode
    environment:
      - CLUSTER_NAME=myhadoop
    networks:
      hadoop-net:
        ipv4_address: 172.25.0.2
    tty: true

  datanode1:
    build: ./hadoop
    container_name: datanode1
    depends_on:
      - namenode
    ports:
      - "2223:22"
    volumes:
      - datanode1-data:/usr/local/hadoop-3.3.6/tmp/datanode
    environment:
      - CLUSTER_NAME=myhadoop
      - NAMENODE_SERVICE_HOST=namenode
    networks:
      hadoop-net:
        ipv4_address: 172.25.0.3
    tty: true

  datanode2:
    build: ./hadoop
    container_name: datanode2
    depends_on:
      - namenode
    ports:
      - "2224:22"
    volumes:
      - datanode2-data:/usr/local/hadoop-3.3.6/tmp/datanode
    environment:
      - CLUSTER_NAME=myhadoop
      - NAMENODE_SERVICE_HOST=namenode
    networks:
      hadoop-net:
        ipv4_address: 172.25.0.4
    tty: true

networks:
  hadoop-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.0.0/16

volumes:
  namenode-data:
  datanode1-data:
  datanode2-data:
